export const trackingVehicles = [
    {
        id: "JH01AB1234",
        type: "Bus",
        model: "Volvo AC Sleeper",
        driver: {
            name: "Rahul Kumar",
            rating: 4.8,
            image: "https://i.pravatar.cc/100?img=1",
            phone: "+91 9876543210",
        },
        speed: 58,
        eta: 32,
        fuel: 68,
        distanceLeft: 45,
        from: "Ranchi",
        to: "Jamshedpur",
        status: "Live",
        scheduleStatus: "On Time",
        updated: "2 min ago",
        location: {
            lat: 23.3441,
            lng: 85.3096,
        },
    },

    {
        id: "JH01CT4567",
        type: "Taxi",
        model: "Sedan",
        driver: {
            name: "Amit Verma",
            rating: 4.6,
            image: "https://i.pravatar.cc/100?img=2",
            phone: "+91 9876543211",
        },
        speed: 45,
        eta: 28,
        fuel: 54,
        distanceLeft: 38,
        from: "Ranchi",
        to: "Bokaro",
        status: "Live",
        scheduleStatus: "On Time",
        updated: "5 min ago",
        location: {
            lat: 23.6693,
            lng: 86.1511,
        },
    },

    {
        id: "JH01MN7890",
        type: "Van",
        model: "Tempo Traveller",
        driver: {
            name: "Raj Singh",
            rating: 4.7,
            image: "https://i.pravatar.cc/100?img=3",
            phone: "+91 9876543212",
        },
        speed: 50,
        eta: 35,
        fuel: 72,
        distanceLeft: 52,
        from: "Ranchi",
        to: "Hazaribagh",
        status: "Live",
        scheduleStatus: "Delayed",
        updated: "3 min ago",
        location: {
            lat: 23.9966,
            lng: 85.3691,
        },
    },

    {
        id: "JH01TR3456",
        type: "Truck",
        model: "Ashok Leyland",
        driver: {
            name: "Suresh Yadav",
            rating: 4.5,
            image: "https://i.pravatar.cc/100?img=4",
            phone: "+91 9876543213",
        },
        speed: 42,
        eta: 50,
        fuel: 61,
        distanceLeft: 90,
        from: "Ranchi",
        to: "Patna",
        status: "Live",
        scheduleStatus: "On Time",
        updated: "4 min ago",
        location: {
            lat: 25.5941,
            lng: 85.1376,
        },
    },

    {
        id: "JH01AU5678",
        type: "Auto",
        model: "Auto Rickshaw",
        driver: {
            name: "Vikash Mahto",
            rating: 4.4,
            image: "https://i.pravatar.cc/100?img=5",
            phone: "+91 9876543214",
        },
        speed: 38,
        eta: 18,
        fuel: 82,
        distanceLeft: 12,
        from: "Ranchi",
        to: "Doranda",
        status: "Live",
        scheduleStatus: "On Time",
        updated: "1 min ago",
        location: {
            lat: 23.3565,
            lng: 85.3346,
        },
    },

    {
        id: "JH01BS9012",
        type: "Bus",
        model: "Scania Luxury",
        driver: {
            name: "Anil Sharma",
            rating: 4.9,
            image: "https://i.pravatar.cc/100?img=6",
            phone: "+91 9876543215",
        },
        speed: 65,
        eta: 22,
        fuel: 74,
        distanceLeft: 30,
        from: "Dhanbad",
        to: "Ranchi",
        status: "Live",
        scheduleStatus: "On Time",
        updated: "2 min ago",
        location: {
            lat: 23.7957,
            lng: 86.4304,
        },
    },

    {
        id: "JH01TX1122",
        type: "Taxi",
        model: "Swift Dzire",
        driver: {
            name: "Pankaj Gupta",
            rating: 4.3,
            image: "https://i.pravatar.cc/100?img=7",
            phone: "+91 9876543216",
        },
        speed: 47,
        eta: 26,
        fuel: 49,
        distanceLeft: 41,
        from: "Bokaro",
        to: "Ranchi",
        status: "Live",
        scheduleStatus: "Delayed",
        updated: "6 min ago",
        location: {
            lat: 23.6693,
            lng: 86.1511,
        },
    },

    {
        id: "JH01VN3344",
        type: "Van",
        model: "Force Traveller",
        driver: {
            name: "Deepak Kumar",
            rating: 4.6,
            image: "https://i.pravatar.cc/100?img=8",
            phone: "+91 9876543217",
        },
        speed: 52,
        eta: 31,
        fuel: 66,
        distanceLeft: 48,
        from: "Ramgarh",
        to: "Ranchi",
        status: "Live",
        scheduleStatus: "On Time",
        updated: "7 min ago",
        location: {
            lat: 23.6307,
            lng: 85.5216,
        },
    },

    {
        id: "JH01TR5566",
        type: "Truck",
        model: "Tata Prima",
        driver: {
            name: "Mukesh Singh",
            rating: 4.2,
            image: "https://i.pravatar.cc/100?img=9",
            phone: "+91 9876543218",
        },
        speed: 40,
        eta: 60,
        fuel: 58,
        distanceLeft: 110,
        from: "Jamshedpur",
        to: "Ranchi",
        status: "Live",
        scheduleStatus: "Delayed",
        updated: "8 min ago",
        location: {
            lat: 22.8046,
            lng: 86.2029,
        },
    },

    {
        id: "JH01BS7788",
        type: "Bus",
        model: "Mercedes Coach",
        driver: {
            name: "Rakesh Kumar",
            rating: 4.8,
            image: "https://i.pravatar.cc/100?img=10",
            phone: "+91 9876543219",
        },
        speed: 62,
        eta: 24,
        fuel: 79,
        distanceLeft: 35,
        from: "Hazaribagh",
        to: "Ranchi",
        status: "Live",
        scheduleStatus: "On Time",
        updated: "2 min ago",
        location: {
            lat: 23.9966,
            lng: 85.3691,
        },
    },
]